# Generated by Django 4.2 on 2025-12-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('OPERATIVO', 'Personal Operativo'), ('GERENCIA', 'Gerencia')], default='OPERATIVO', help_text='Rol del usuario en el sistema', max_length=50),
        ),
    ]
