# Generated by Django 4.2 on 2025-11-10 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_de_caducidad',
            new_name='fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
